### ISSUE TITLE
Wrong Draw

### ISSUE THREAD

**Issue by PratyushGautamDev** [thehamzaihsan/tictactoe-react-ts#1]
![Screenshot (15)](https://github.com/thehamzaihsan/tictactoe-react-ts/assets/144725948/387668eb-d20d-4ded-902b-53378b140c9f)
![Screenshot (16)](https://github.com/thehamzaihsan/tictactoe-react-ts/assets/144725948/f42afc23-6894-4f0d-a097-a3824cda25af)

**Comment by thehamzaihsan** [comment]
Hi there, Thanks for reporting!!! 
I will fix this in a few days 😀.
Can you share me the moves which led to this bug.

**Comment by PratyushGautamDev** [comment]
Sure, here are the steps

https://github.com/thehamzaihsan/tictactoe-react-ts/assets/144725948/e13b9783-6d34-48b1-8480-1a1378f5b1af

**Comment by PratyushGautamDev** [comment]
Sure, heare are the moves

https://github.com/thehamzaihsan/tictactoe-react-ts/assets/144725948/1ce43377-ce0b-4f7c-9bae-59f0b2451c05
